from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
import json
import base64
import requests
import os
import tempfile
from PIL import Image
import io
from .models import Client, File
from django.conf import settings


# Helper functions for API calls
def call_gemini_api(request_body, use_vision=False):
    api_key = settings.GEMINI_API_KEY
    if not api_key:
        raise ValueError("API key not configured.")
   
    # Use different model for vision vs text tasks
    if use_vision:
        model = "gemini-1.5-flash"
    else:
        model = "gemini-1.5-flash"
    
    api_url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={api_key}"
   
    headers = {
        'Content-Type': 'application/json'
    }
   
    try:
        print(f"Making API call to: {api_url}")
        print(f"Request body: {json.dumps(request_body, indent=2)}")
        
        response = requests.post(api_url, data=json.dumps(request_body), headers=headers)
        print(f"Response status: {response.status_code}")
        print(f"Response content: {response.text}")
        
        response.raise_for_status()
        data = response.json()
        
        if 'candidates' in data and len(data['candidates']) > 0:
            if 'content' in data['candidates'][0] and 'parts' in data['candidates'][0]['content']:
                text = data['candidates'][0]['content']['parts'][0]['text']
                return text
            else:
                print("Unexpected response structure")
                return "Error: Unexpected API response structure"
        else:
            print("No candidates in response")
            return "Error: No content generated by API"
            
    except requests.exceptions.RequestException as e:
        print(f"API Request Error: {e}")
        if hasattr(e, 'response') and e.response is not None:
            print(f"Error response: {e.response.text}")
        raise e
    except Exception as e:
        print(f"General API Error: {e}")
        raise e


def extract_text_from_image(base64_image, mime_type):
    """Extract text from image using Gemini Vision API"""
    request_body = {
        "contents": [{
            "parts": [
                {"text": "Extract all text, including handwritten text, from this image. Return only the extracted text without any additional formatting or commentary. If no text is found, return 'No text detected'."},
                {"inlineData": {"mimeType": mime_type, "data": base64_image}}
            ]
        }],
        "generationConfig": {
            "temperature": 0.1,
            "maxOutputTokens": 2048
        }
    }
    return call_gemini_api(request_body, use_vision=True)


def generate_summary(text):
    """Generate summary of extracted text"""
    if not text or text.strip() in ['', 'No text detected', 'No text found']:
        return "No text available to summarize"
        
    request_body = {
        "contents": [{
            "parts": [{"text": f"Create a concise legal document summary from the following text. Focus on key points, entities, dates, and legal implications. If the text is not legal-related, provide a general summary:\n\n{text}"}]
        }],
        "generationConfig": {
            "temperature": 0.3,
            "maxOutputTokens": 1024
        }
    }
    return call_gemini_api(request_body, use_vision=False)


def login_view(request):
    if request.user.is_authenticated:
        return redirect('dashboard')
    
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            messages.success(request, 'Welcome back!')
            return redirect('dashboard')
        else:
            messages.error(request, 'Invalid username or password.')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


def register_view(request):
    if request.user.is_authenticated:
        return redirect('dashboard')
        
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, f'Welcome {user.username}! Your account has been created.')
            return redirect('dashboard')
        else:
            messages.error(request, 'Please correct the errors below.')
    else:
        form = UserCreationForm()
   
    return render(request, 'register.html', {'form': form})


@login_required
def dashboard_view(request):
    # Get some statistics for the dashboard
    client_count = Client.objects.filter(user=request.user).count()
    file_count = File.objects.filter(client__user=request.user).count()
    recent_clients = Client.objects.filter(user=request.user).order_by('-created_at')[:3]
    
    context = {
        'user': request.user,
        'client_count': client_count,
        'file_count': file_count,
        'recent_clients': recent_clients,
    }
    return render(request, 'dashboard.html', context)


@login_required
def add_client_view(request):
    if request.method == 'POST':
        client_name = request.POST.get('client_name', '').strip()
        
        if not client_name:
            messages.error(request, 'Client name is required.')
            return render(request, 'new_client.html')
        
        # Create new client
        client = Client.objects.create(
            user=request.user,
            full_name=client_name
        )
        
        print(f"Created client: {client.full_name}")
        
        # Process uploaded files
        files = request.FILES.getlist('files')
        processed_files = []
        errors = []
        
        print(f"Processing {len(files)} files")
        
        for uploaded_file in files:
            try:
                print(f"Processing file: {uploaded_file.name}, type: {uploaded_file.content_type}")
                
                # Validate file type
                if not uploaded_file.content_type.startswith('image/'):
                    error_msg = f"File {uploaded_file.name} is not an image."
                    errors.append(error_msg)
                    print(error_msg)
                    continue
                
                # Read and encode the file
                uploaded_file.seek(0)  # Reset file pointer
                file_content = uploaded_file.read()
                print(f"File size: {len(file_content)} bytes")
                
                if len(file_content) == 0:
                    error_msg = f"File {uploaded_file.name} is empty."
                    errors.append(error_msg)
                    print(error_msg)
                    continue
                
                base64_image = base64.b64encode(file_content).decode('utf-8')
                print(f"Base64 encoded, length: {len(base64_image)}")
                
                # Extract text using Gemini API
                print("Calling extract_text_from_image...")
                try:
                    extracted_text = extract_text_from_image(base64_image, uploaded_file.content_type)
                    print(f"Extracted text: {extracted_text[:200]}...")
                except Exception as e:
                    print(f"Text extraction failed: {str(e)}")
                    extracted_text = f"Text extraction failed: {str(e)}"
                
                # Generate summary
                print("Generating summary...")
                try:
                    if extracted_text and not extracted_text.startswith("Error:") and not extracted_text.startswith("Text extraction failed:"):
                        summary = generate_summary(extracted_text)
                        print(f"Generated summary: {summary[:200]}...")
                    else:
                        summary = "No text found to summarize."
                        print("No valid text for summary")
                except Exception as e:
                    print(f"Summary generation failed: {str(e)}")
                    summary = f"Summary generation failed: {str(e)}"
                
                # Save file to database
                file_obj = File.objects.create(
                    client=client,
                    name=uploaded_file.name,
                    file_type=uploaded_file.content_type,
                    file_size=len(file_content),
                    extracted_text=extracted_text,
                    content=summary,  # Store summary in content field
                    processed=True
                )
                processed_files.append(file_obj)
                print(f"Saved file to database: {file_obj.id}")
                
            except Exception as e:
                error_msg = f"Error processing {uploaded_file.name}: {str(e)}"
                errors.append(error_msg)
                print(f"File processing error: {error_msg}")
        
        # Update client case summary with combined summaries
        if processed_files:
            try:
                summaries = []
                for f in processed_files:
                    if f.content and not f.content.startswith("Error:") and not f.content.startswith("Summary generation failed:"):
                        summaries.append(f.content)
                
                if summaries:
                    combined_summary = " | ".join(summaries)
                    # Truncate if too long
                    if len(combined_summary) > 1000:
                        combined_summary = combined_summary[:1000] + "..."
                    client.case_summary = combined_summary
                    client.save()
                    print(f"Updated client case summary: {combined_summary[:100]}...")
                else:
                    client.case_summary = "Files processed but no summaries could be generated."
                    client.save()
            except Exception as e:
                print(f"Error updating case summary: {str(e)}")
        
        # Show results to user
        if errors:
            for error in errors:
                messages.error(request, error)
        
        if processed_files:
            success_msg = f'Client "{client_name}" created successfully with {len(processed_files)} processed file(s).'
            messages.success(request, success_msg)
            print(success_msg)
            return redirect('existing_clients')
        else:
            error_msg = 'Client created but no files were successfully processed.'
            messages.error(request, error_msg)
            print(error_msg)
    
    return render(request, 'new_client.html')


@login_required
def existing_clients_view(request):
    clients = Client.objects.filter(user=request.user).order_by('-created_at')
    
    # Add file count to each client
    for client in clients:
        client.file_count = File.objects.filter(client=client).count()
    
    return render(request, 'existing_clients.html', {'clients': clients})


@login_required
def all_files_view(request):
    files = File.objects.filter(client__user=request.user).select_related('client').order_by('-uploaded_at')
    return render(request, 'all_files.html', {'files': files})


@login_required
def client_detail_view(request, client_id):
    client = get_object_or_404(Client, id=client_id, user=request.user)
    files = File.objects.filter(client=client).order_by('-uploaded_at')
    return render(request, 'client_detail.html', {'client': client, 'files': files})


@login_required
def delete_client_view(request, client_id):
    client = get_object_or_404(Client, id=client_id, user=request.user)
    if request.method == 'POST':
        client_name = client.full_name
        client.delete()
        messages.success(request, f'Client "{client_name}" has been deleted.')
        return redirect('existing_clients')
    return render(request, 'confirm_delete.html', {'client': client})


@login_required
def file_detail_view(request, file_id):
    file_obj = get_object_or_404(File, id=file_id, client__user=request.user)
    return JsonResponse({
        'name': file_obj.name,
        'client': file_obj.client.full_name,
        'extracted_text': file_obj.extracted_text or 'No text extracted',
        'summary': file_obj.content or 'No summary available',
        'uploaded_at': file_obj.uploaded_at.strftime('%Y-%m-%d %H:%M:%S')
    })


def logout_view(request):
    logout(request)
    messages.success(request, 'You have been successfully logged out.')
    return redirect('login')


# API endpoint for processing individual files (for AJAX requests)
@csrf_exempt
@login_required
def process_file_api(request):
    if request.method == 'POST':
        try:
            client_id = request.POST.get('client_id')
            uploaded_file = request.FILES.get('file')

            print(f"API: Processing file for client {client_id}")

            if not uploaded_file:
                return JsonResponse({'success': False, 'error': 'No file uploaded.'}, status=400)

            if not uploaded_file.content_type.startswith('image/'):
                return JsonResponse({'success': False, 'error': 'Only image files are supported.'}, status=400)

            # Get the client object
            client = get_object_or_404(Client, id=client_id, user=request.user)

            # Read and encode the image
            uploaded_file.seek(0)  # Reset file pointer
            file_content = uploaded_file.read()
            
            if len(file_content) == 0:
                return JsonResponse({'success': False, 'error': 'Uploaded file is empty.'}, status=400)
                
            base64_image = base64.b64encode(file_content).decode('utf-8')

            print(f"API: File encoded, size: {len(file_content)} bytes")

            # Extract text using Gemini API
            try:
                extracted_text = extract_text_from_image(base64_image, uploaded_file.content_type)
                print(f"API: Text extracted: {extracted_text[:100]}...")
            except Exception as e:
                print(f"API: Text extraction error: {str(e)}")
                return JsonResponse({'success': False, 'error': f'Text extraction failed: {str(e)}'}, status=500)
            
            # Generate summary
            try:
                if extracted_text and not extracted_text.startswith("Error:"):
                    summary = generate_summary(extracted_text)
                    print(f"API: Summary generated: {summary[:100]}...")
                else:
                    summary = "No text found to summarize."
            except Exception as e:
                print(f"API: Summary generation error: {str(e)}")
                summary = f"Summary generation failed: {str(e)}"

            # Save file to database
            file_obj = File.objects.create(
                client=client,
                name=uploaded_file.name,
                file_type=uploaded_file.content_type,
                file_size=len(file_content),
                extracted_text=extracted_text,
                content=summary,
                processed=True
            )

            print(f"API: File saved to database: {file_obj.id}")

            return JsonResponse({
                'success': True,
                'file_id': file_obj.id,
                'extracted_text': extracted_text,
                'summary': summary
            })

        except Client.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Client not found.'}, status=404)
        except Exception as e:
            print(f"API: General error: {str(e)}")
            return JsonResponse({'success': False, 'error': f'Error processing file: {str(e)}'}, status=500)
   
    return JsonResponse({'success': False, 'error': 'Invalid request method.'}, status=405)




































